# Generated by Django 5.0.6 on 2026-06-10 23:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0012_alter_minigamerecord_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='minigamerecord',
            unique_together={('user', 'game_code')},
        ),
    ]
